mongodb-init:
	pnpm dlx prisma init --datasource-provider mongodb --output ../generated/prisma

migrate-nosql:
	pnpm migrate:nosql

seed:
	pnpm seed

reset:
	pnpm reset

studio-dev:
	pnpm studio:dev

dev:
	pnpm start:dev
