import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { UserRole } from 'generated/prisma';
import { PrismaService } from 'src/providers/prisma.service';
import * as bcrypt from 'bcrypt';

@Injectable()
export class SeedService implements OnModuleInit {
  private readonly logger = new Logger(SeedService.name);

  constructor(private readonly prisma: PrismaService) {}

  async onModuleInit() {
    await this.seed();
  }

  async seed() {
    const userCount = await this.prisma.user.count();
    if (userCount > 0) {
      this.logger.log('Database đã có dữ liệu, bỏ qua seed.');
      return;
    }

    await this.prisma.user.createMany({
      data: [
        {
          email: 'anhkhoi123@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Lê Anh Khôi',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Lê Anh Khôi')}`,
          emailVerified: true,
          fvtBalance: 1000,
          address: {
            houseNumber: '1',
            street: 'Lê Lợi',
            commune: 'Phường 1',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer2@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trần Thị B',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Trần Thị B')}`,
          emailVerified: true,
          fvtBalance: 900,
          address: {
            houseNumber: '2',
            street: 'Nguyễn Huệ',
            commune: 'Phường 2',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer3@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Lê Văn C',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Lê Văn C')}`,
          emailVerified: true,
          fvtBalance: 800,
          address: {
            houseNumber: '3',
            street: 'Trần Phú',
            commune: 'Phường 3',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer4@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Phạm Thị D',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Phạm Thị D')}`,
          emailVerified: true,
          fvtBalance: 700,
          address: {
            houseNumber: '4',
            street: 'Bùi Thị Xuân',
            commune: 'Phường 4',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer5@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Vũ Văn E',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Vũ Văn E')}`,
          emailVerified: true,
          fvtBalance: 600,
          address: {
            houseNumber: '5',
            street: 'Nguyễn Trãi',
            commune: 'Phường 5',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer6@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Đặng Thị F',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Đặng Thị F')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '6',
            street: 'Lý Thường Kiệt',
            commune: 'Phường 6',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer7@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Ngô Văn G',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Ngô Văn G')}`,
          emailVerified: true,
          fvtBalance: 400,
          address: {
            houseNumber: '7',
            street: 'Phan Chu Trinh',
            commune: 'Phường 7',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer8@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Bùi Thị H',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Bùi Thị H')}`,
          emailVerified: true,
          fvtBalance: 300,
          address: {
            houseNumber: '8',
            street: 'Trần Hưng Đạo',
            commune: 'Phường 8',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer9@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Lý Văn I',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Lý Văn I')}`,
          emailVerified: true,
          fvtBalance: 200,
          address: {
            houseNumber: '9',
            street: 'Nguyễn Du',
            commune: 'Phường 9',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'farmer10@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trịnh Thị K',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Trịnh Thị K')}`,
          emailVerified: true,
          fvtBalance: 100,
          address: {
            houseNumber: '10',
            street: 'Quang Trung',
            commune: 'Phường 10',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        // 10 Tenants
        {
          email: 'tenant1@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Phạm Văn L',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Phạm Văn L')}`,
          emailVerified: true,
          fvtBalance: 1000,
          address: {
            houseNumber: '11',
            street: 'Lê Lợi',
            commune: 'Phường 1',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant2@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trần Thị M',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Trần Thị M')}`,
          emailVerified: true,
          fvtBalance: 900,
          address: {
            houseNumber: '12',
            street: 'Nguyễn Huệ',
            commune: 'Phường 2',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant3@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Lê Văn N',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Lê Văn N')}`,
          emailVerified: true,
          fvtBalance: 800,
          address: {
            houseNumber: '13',
            street: 'Trần Phú',
            commune: 'Phường 3',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant4@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Phạm Thị O',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Phạm Thị O')}`,
          emailVerified: true,
          fvtBalance: 700,
          address: {
            houseNumber: '14',
            street: 'Bùi Thị Xuân',
            commune: 'Phường 4',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant5@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Vũ Văn P',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Vũ Văn P')}`,
          emailVerified: true,
          fvtBalance: 600,
          address: {
            houseNumber: '15',
            street: 'Nguyễn Trãi',
            commune: 'Phường 5',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant6@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Đặng Thị Q',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Đặng Thị Q')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '16',
            street: 'Lý Thường Kiệt',
            commune: 'Phường 6',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant7@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Ngô Văn R',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Ngô Văn R')}`,
          emailVerified: true,
          fvtBalance: 400,
          address: {
            houseNumber: '17',
            street: 'Phan Chu Trinh',
            commune: 'Phường 7',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant8@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Bùi Thị S',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Bùi Thị S')}`,
          emailVerified: true,
          fvtBalance: 300,
          address: {
            houseNumber: '18',
            street: 'Trần Hưng Đạo',
            commune: 'Phường 8',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant9@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Lý Văn T',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Lý Văn T')}`,
          emailVerified: true,
          fvtBalance: 200,
          address: {
            houseNumber: '19',
            street: 'Nguyễn Du',
            commune: 'Phường 9',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'tenant10@example.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trịnh Thị U',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Trịnh Thị U')}`,
          emailVerified: true,
          fvtBalance: 100,
          address: {
            houseNumber: '20',
            street: 'Quang Trung',
            commune: 'Phường 10',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'nduc42176@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trần Đình Phúc Đức',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Trần Đình Phúc Đức')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '10',
            street: 'Huỳnh Văn Nghệ',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'khaibetatc@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Hà Vũ Khải',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Hà Vũ Khải')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '22',
            street: 'Hồ Văn Đại',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'Hak398113@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'KHải Vũ Hà',
          role: UserRole.FARMER,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Khải Vũ Hà')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '22',
            street: 'Hồ Văn Đại',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'nguyentrungnghia.lhu@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Nguyễn Trung Nghĩa',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Nguyễn Trung Nghĩa')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '232',
            street: 'Ngô Quyền',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: '23112004dejavu@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Nghĩa Trung Nguyễn',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent('Nghĩa Trung Nguyễn')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '232',
            street: 'Ngô Quyền',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
        {
          email: 'battlegroundplay@gmail.com',
          password: await bcrypt.hash('123456', 10),
          name: 'Trung Nguyễn Nghĩa',
          role: UserRole.TENANT,
          avatar: `https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(' Trung Nguyễn Nghĩa')}`,
          emailVerified: true,
          fvtBalance: 500,
          address: {
            houseNumber: '232',
            street: 'Ngô Quyền',
            commune: 'Phường Trấn Biên',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
        },
      ],
    });
    await this.prisma.farm.createMany({
      data: [
        {
          name: 'Trang trại Vải thiều',
          address: {
            houseNumber: '1',
            street: 'Lê Lợi',
            commune: 'Phường 1',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 100,
          description: 'Trang trại cây ăn quả lâu năm chuyên Vải thiều',
          images: ['https://example.com/farm-vai-thieu.jpg'],
          schedule: [],
          userId: 'user1-id',
        },
        {
          name: 'Trang trại Xoài cát',
          address: {
            houseNumber: '2',
            street: 'Nguyễn Huệ',
            commune: 'Phường 2',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 120,
          description: 'Trang trại cây ăn quả lâu năm chuyên Xoài cát',
          images: ['https://example.com/farm-xoai-cat.jpg'],
          schedule: [],
          userId: 'user2-id',
        },
        {
          name: 'Trang trại Mít thái',
          address: {
            houseNumber: '3',
            street: 'Trần Phú',
            commune: 'Phường 3',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 130,
          description: 'Trang trại cây ăn quả lâu năm chuyên Mít thái',
          images: ['https://example.com/farm-mit-thai.jpg'],
          schedule: [],
          userId: 'user3-id',
        },
        {
          name: 'Trang trại Sầu riêng',
          address: {
            houseNumber: '4',
            street: 'Bùi Thị Xuân',
            commune: 'Phường 4',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 140,
          description: 'Trang trại cây ăn quả lâu năm chuyên Sầu riêng',
          images: ['https://example.com/farm-sau-rieng.jpg'],
          schedule: [],
          userId: 'user4-id',
        },
        {
          name: 'Trang trại Chôm chôm',
          address: {
            houseNumber: '5',
            street: 'Nguyễn Trãi',
            commune: 'Phường 5',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 150,
          description: 'Trang trại cây ăn quả lâu năm chuyên Chôm chôm',
          images: ['https://example.com/farm-chom-chom.jpg'],
          schedule: [],
          userId: 'user5-id',
        },
        {
          name: 'Trang trại Măng cụt',
          address: {
            houseNumber: '6',
            street: 'Lý Thường Kiệt',
            commune: 'Phường 6',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 160,
          description: 'Trang trại cây ăn quả lâu năm chuyên Măng cụt',
          images: ['https://example.com/farm-mang-cut.jpg'],
          schedule: [],
          userId: 'user6-id',
        },
        {
          name: 'Trang trại Bưởi da xanh',
          address: {
            houseNumber: '7',
            street: 'Phan Chu Trinh',
            commune: 'Phường 7',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 170,
          description: 'Trang trại cây ăn quả lâu năm chuyên Bưởi da xanh',
          images: ['https://example.com/farm-buoi-da-xanh.jpg'],
          schedule: [],
          userId: 'user7-id',
        },
        {
          name: 'Trang trại Cam sành',
          address: {
            houseNumber: '8',
            street: 'Trần Hưng Đạo',
            commune: 'Phường 8',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 180,
          description: 'Trang trại cây ăn quả lâu năm chuyên Cam sành',
          images: ['https://example.com/farm-cam-sanh.jpg'],
          schedule: [],
          userId: 'user8-id',
        },
        {
          name: 'Trang trại Thanh long',
          address: {
            houseNumber: '9',
            street: 'Nguyễn Du',
            commune: 'Phường 9',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 190,
          description: 'Trang trại cây ăn quả lâu năm chuyên Thanh long',
          images: ['https://example.com/farm-thanh-long.jpg'],
          schedule: [],
          userId: 'user9-id',
        },
        {
          name: 'Trang trại Dừa xiêm',
          address: {
            houseNumber: '10',
            street: 'Quang Trung',
            commune: 'Phường 10',
            province: 'Đồng Nai',
            country: 'Việt Nam',
          },
          size: 200,
          description: 'Trang trại cây ăn quả lâu năm chuyên Dừa xiêm',
          images: ['https://example.com/farm-dua-xiem.jpg'],
          schedule: [],
          userId: 'user10-id',
        },
      ],
    });
    await this.prisma.item.createMany({
      data: [
        {
          name: 'Vải thiều',
          type: 'TREE',
          description: 'Vải thiều tươi ngon',
          images: ['https://example.com/item-vai-thieu.jpg'],
          price: 50000,
          stock: 100,
          details: {},
          farmId: '1',
        },
        {
          name: 'Xoài cát',
          type: 'TREE',
          description: 'Xoài cát ngọt',
          images: ['https://example.com/item-xoai-cat.jpg'],
          price: 40000,
          stock: 100,
          details: {},
          farmId: '2',
        },
        {
          name: 'Mít thái',
          type: 'TREE',
          description: 'Mít thái thơm ngon',
          images: ['https://example.com/item-mit-thai.jpg'],
          price: 35000,
          stock: 100,
          details: {},
          farmId: '3',
        },
        {
          name: 'Sầu riêng',
          type: 'TREE',
          description: 'Sầu riêng chín cây',
          images: ['https://example.com/item-sau-rieng.jpg'],
          price: 120000,
          stock: 100,
          details: {},
          farmId: '4',
        },
        {
          name: 'Chôm chôm',
          type: 'TREE',
          description: 'Chôm chôm đỏ tươi',
          images: ['https://example.com/item-chom-chom.jpg'],
          price: 45000,
          stock: 100,
          details: {},
          farmId: '5',
        },
        {
          name: 'Măng cụt',
          type: 'TREE',
          description: 'Măng cụt ngọt',
          images: ['https://example.com/item-mang-cut.jpg'],
          price: 60000,
          stock: 100,
          details: {},
          farmId: '6',
        },
        {
          name: 'Bưởi da xanh',
          type: 'TREE',
          description: 'Bưởi da xanh mọng nước',
          images: ['https://example.com/item-buoi-da-xanh.jpg'],
          price: 70000,
          stock: 100,
          details: {},
          farmId: '7',
        },
        {
          name: 'Cam sành',
          type: 'TREE',
          description: 'Cam sành tươi',
          images: ['https://example.com/item-cam-sanh.jpg'],
          price: 30000,
          stock: 100,
          details: {},
          farmId: '8',
        },
        {
          name: 'Thanh long',
          type: 'TREE',
          description: 'Thanh long ruột đỏ',
          images: ['https://example.com/item-thanh-long.jpg'],
          price: 25000,
          stock: 100,
          details: {},
          farmId: '9',
        },
        {
          name: 'Dừa xiêm',
          type: 'TREE',
          description: 'Dừa xiêm ngọt mát',
          images: ['https://example.com/item-dua-xiem.jpg'],
          price: 20000,
          stock: 100,
          details: {},
          farmId: '10',
        },
        {
          name: 'Thuốc trừ sâu Anvil',
          type: 'PESTICIDE',
          description: 'Hiệu quả phòng trừ sâu bệnh',
          images: ['https://example.com/item-anvil.jpg'],
          price: 80000,
          stock: 50,
          details: {},
          farmId: '1',
        },
        {
          name: 'Thuốc trừ cỏ Glyphosate',
          type: 'PESTICIDE',
          description: 'Diệt cỏ nhanh chóng',
          images: ['https://example.com/item-glyphosate.jpg'],
          price: 60000,
          stock: 50,
          details: {},
          farmId: '2',
        },
        {
          name: 'Thuốc trừ sâu Regent',
          type: 'PESTICIDE',
          description: 'Diệt sâu hiệu quả',
          images: ['https://example.com/item-regent.jpg'],
          price: 90000,
          stock: 50,
          details: {},
          farmId: '3',
        },
        {
          name: 'Thuốc trừ bệnh Ridomil',
          type: 'PESTICIDE',
          description: 'Phòng trừ nấm bệnh',
          images: ['https://example.com/item-ridomil.jpg'],
          price: 85000,
          stock: 50,
          details: {},
          farmId: '4',
        },
        {
          name: 'Thuốc trừ sâu Confidor',
          type: 'PESTICIDE',
          description: 'Diệt rầy nâu',
          images: ['https://example.com/item-confidor.jpg'],
          price: 95000,
          stock: 50,
          details: {},
          farmId: '5',
        },
        {
          name: 'Thuốc trừ sâu Karate',
          type: 'PESTICIDE',
          description: 'Diệt sâu cuốn lá',
          images: ['https://example.com/item-karate.jpg'],
          price: 70000,
          stock: 50,
          details: {},
          farmId: '6',
        },
        {
          name: 'Thuốc trừ sâu Map',
          type: 'PESTICIDE',
          description: 'Diệt sâu tơ',
          images: ['https://example.com/item-map.jpg'],
          price: 75000,
          stock: 50,
          details: {},
          farmId: '7',
        },
        {
          name: 'Thuốc trừ sâu Basudin',
          type: 'PESTICIDE',
          description: 'Diệt sâu đất',
          images: ['https://example.com/item-basudin.jpg'],
          price: 65000,
          stock: 50,
          details: {},
          farmId: '8',
        },
        {
          name: 'Thuốc trừ sâu Selecron',
          type: 'PESTICIDE',
          description: 'Diệt sâu đục thân',
          images: ['https://example.com/item-selecron.jpg'],
          price: 80000,
          stock: 50,
          details: {},
          farmId: '9',
        },
        {
          name: 'Thuốc trừ sâu Sumi-alpha',
          type: 'PESTICIDE',
          description: 'Diệt sâu đầu đen',
          images: ['https://example.com/item-sumialpha.jpg'],
          price: 90000,
          stock: 50,
          details: {},
          farmId: '10',
        },
        // FERTILIZER items
        {
          name: 'Phân bón NPK 16-16-8',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-16-16-8.jpg'],
          price: 40000,
          stock: 200,
          details: {},
          farmId: '1',
        },
        {
          name: 'Phân bón hữu cơ vi sinh',
          type: 'FERTILIZER',
          description: 'Cải tạo đất, tăng năng suất',
          images: ['https://example.com/item-huu-co.jpg'],
          price: 50000,
          stock: 200,
          details: {},
          farmId: '2',
        },
        {
          name: 'Phân bón DAP',
          type: 'FERTILIZER',
          description: 'Phân bón giàu đạm',
          images: ['https://example.com/item-dap.jpg'],
          price: 60000,
          stock: 200,
          details: {},
          farmId: '3',
        },
        {
          name: 'Phân bón Kali',
          type: 'FERTILIZER',
          description: 'Giúp cây phát triển rễ',
          images: ['https://example.com/item-kali.jpg'],
          price: 45000,
          stock: 200,
          details: {},
          farmId: '4',
        },
        {
          name: 'Phân bón Urea',
          type: 'FERTILIZER',
          description: 'Phân bón giàu đạm',
          images: ['https://example.com/item-urea.jpg'],
          price: 55000,
          stock: 200,
          details: {},
          farmId: '5',
        },
        {
          name: 'Phân bón NPK 20-20-15',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-20-20-15.jpg'],
          price: 42000,
          stock: 200,
          details: {},
          farmId: '6',
        },
        {
          name: 'Phân bón Super Lân',
          type: 'FERTILIZER',
          description: 'Giúp cây ra hoa',
          images: ['https://example.com/item-superlan.jpg'],
          price: 48000,
          stock: 200,
          details: {},
          farmId: '7',
        },
        {
          name: 'Phân bón vi lượng',
          type: 'FERTILIZER',
          description: 'Bổ sung vi chất',
          images: ['https://example.com/item-vi-luong.jpg'],
          price: 52000,
          stock: 200,
          details: {},
          farmId: '8',
        },
        {
          name: 'Phân bón hữu cơ sinh học',
          type: 'FERTILIZER',
          description: 'Tăng sức đề kháng',
          images: ['https://example.com/item-huu-co-sinh-hoc.jpg'],
          price: 53000,
          stock: 200,
          details: {},
          farmId: '9',
        },
        {
          name: 'Phân bón NPK 15-15-15',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-15-15-15.jpg'],
          price: 41000,
          stock: 200,
          details: {},
          farmId: '10',
        },
        {
          name: 'Thuốc trừ sâu Anvil',
          type: 'PESTICIDE',
          description: 'Hiệu quả phòng trừ sâu bệnh',
          images: ['https://example.com/item-anvil.jpg'],
          price: 80000,
          stock: 50,
          details: {},
          farmId: '1',
        },
        {
          name: 'Thuốc trừ cỏ Glyphosate',
          type: 'PESTICIDE',
          description: 'Diệt cỏ nhanh chóng',
          images: ['https://example.com/item-glyphosate.jpg'],
          price: 60000,
          stock: 50,
          details: {},
          farmId: '2',
        },
        {
          name: 'Thuốc trừ sâu Regent',
          type: 'PESTICIDE',
          description: 'Diệt sâu hiệu quả',
          images: ['https://example.com/item-regent.jpg'],
          price: 90000,
          stock: 50,
          details: {},
          farmId: '3',
        },
        {
          name: 'Thuốc trừ bệnh Ridomil',
          type: 'PESTICIDE',
          description: 'Phòng trừ nấm bệnh',
          images: ['https://example.com/item-ridomil.jpg'],
          price: 85000,
          stock: 50,
          details: {},
          farmId: '4',
        },
        {
          name: 'Thuốc trừ sâu Confidor',
          type: 'PESTICIDE',
          description: 'Diệt rầy nâu',
          images: ['https://example.com/item-confidor.jpg'],
          price: 95000,
          stock: 50,
          details: {},
          farmId: '5',
        },
        {
          name: 'Thuốc trừ sâu Karate',
          type: 'PESTICIDE',
          description: 'Diệt sâu cuốn lá',
          images: ['https://example.com/item-karate.jpg'],
          price: 70000,
          stock: 50,
          details: {},
          farmId: '6',
        },
        {
          name: 'Thuốc trừ sâu Map',
          type: 'PESTICIDE',
          description: 'Diệt sâu tơ',
          images: ['https://example.com/item-map.jpg'],
          price: 75000,
          stock: 50,
          details: {},
          farmId: '7',
        },
        {
          name: 'Thuốc trừ sâu Basudin',
          type: 'PESTICIDE',
          description: 'Diệt sâu đất',
          images: ['https://example.com/item-basudin.jpg'],
          price: 65000,
          stock: 50,
          details: {},
          farmId: '8',
        },
        {
          name: 'Thuốc trừ sâu Selecron',
          type: 'PESTICIDE',
          description: 'Diệt sâu đục thân',
          images: ['https://example.com/item-selecron.jpg'],
          price: 80000,
          stock: 50,
          details: {},
          farmId: '9',
        },
        {
          name: 'Thuốc trừ sâu Sumi-alpha',
          type: 'PESTICIDE',
          description: 'Diệt sâu đầu đen',
          images: ['https://example.com/item-sumialpha.jpg'],
          price: 90000,
          stock: 50,
          details: {},
          farmId: '10',
        },
        {
          name: 'Phân bón NPK 16-16-8',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-16-16-8.jpg'],
          price: 40000,
          stock: 200,
          details: {},
          farmId: '1',
        },
        {
          name: 'Phân bón hữu cơ vi sinh',
          type: 'FERTILIZER',
          description: 'Cải tạo đất, tăng năng suất',
          images: ['https://example.com/item-huu-co.jpg'],
          price: 50000,
          stock: 200,
          details: {},
          farmId: '2',
        },
        {
          name: 'Phân bón DAP',
          type: 'FERTILIZER',
          description: 'Phân bón giàu đạm',
          images: ['https://example.com/item-dap.jpg'],
          price: 60000,
          stock: 200,
          details: {},
          farmId: '3',
        },
        {
          name: 'Phân bón Kali',
          type: 'FERTILIZER',
          description: 'Giúp cây phát triển rễ',
          images: ['https://example.com/item-kali.jpg'],
          price: 45000,
          stock: 200,
          details: {},
          farmId: '4',
        },
        {
          name: 'Phân bón Urea',
          type: 'FERTILIZER',
          description: 'Phân bón giàu đạm',
          images: ['https://example.com/item-urea.jpg'],
          price: 55000,
          stock: 200,
          details: {},
          farmId: '5',
        },
        {
          name: 'Phân bón NPK 20-20-15',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-20-20-15.jpg'],
          price: 42000,
          stock: 200,
          details: {},
          farmId: '6',
        },
        {
          name: 'Phân bón Super Lân',
          type: 'FERTILIZER',
          description: 'Giúp cây ra hoa',
          images: ['https://example.com/item-superlan.jpg'],
          price: 48000,
          stock: 200,
          details: {},
          farmId: '7',
        },
        {
          name: 'Phân bón vi lượng',
          type: 'FERTILIZER',
          description: 'Bổ sung vi chất',
          images: ['https://example.com/item-vi-luong.jpg'],
          price: 52000,
          stock: 200,
          details: {},
          farmId: '8',
        },
        {
          name: 'Phân bón hữu cơ sinh học',
          type: 'FERTILIZER',
          description: 'Tăng sức đề kháng',
          images: ['https://example.com/item-huu-co-sinh-hoc.jpg'],
          price: 53000,
          stock: 200,
          details: {},
          farmId: '9',
        },
        {
          name: 'Phân bón NPK 15-15-15',
          type: 'FERTILIZER',
          description: 'Phân bón đa lượng',
          images: ['https://example.com/item-npk-15-15-15.jpg'],
          price: 41000,
          stock: 200,
          details: {},
          farmId: '10',
        },
      ],
    });
    this.logger.log('Seed dữ liệu thành công!');
  }
}
